import { NextRequest, NextResponse } from 'next/server'
import Papa from 'papaparse'
import type { ChartOfAccounts, Transaction } from '@/types'
import { canonicalizeTransactionForExport, validateTransactionsForExport } from '@/lib/exportValidation'
import { requireRouteAccess } from '@/lib/routeSubscription'

type ExportFormat = 'quickbooks' | 'standard'

interface RequestBody {
  transactions: Transaction[]
  chartOfAccounts: ChartOfAccounts[]
  clientName: string
  format: ExportFormat
}

function isValidBody(body: unknown): body is RequestBody {
  if (!body || typeof body !== 'object') return false
  const b = body as Record<string, unknown>
  return (
    Array.isArray(b.transactions) &&
    Array.isArray(b.chartOfAccounts) &&
    typeof b.clientName === 'string' &&
    b.clientName.trim().length > 0 &&
    (b.format === 'quickbooks' || b.format === 'standard')
  )
}

function safeFilename(name: string): string {
  return name.trim().replace(/[^a-zA-Z0-9_\-. ]/g, '_').replace(/\s+/g, '_')
}

// ---------------------------------------------------------------------------
// QuickBooks CSV
// Columns QuickBooks Desktop / Online import expects:
//   Date, Account, Description, Amount, Category, Class
// Debits are negative amounts on the bank account line.
// ---------------------------------------------------------------------------
function buildQuickBooksCSV(transactions: Transaction[], clientName: string, chartOfAccounts: ChartOfAccounts[]): string {
  const rows = transactions.map((transaction) => {
    const t = canonicalizeTransactionForExport(transaction, chartOfAccounts)
    const category = t.final_category ?? t.suggested_category ?? 'Uncategorized'
    const account  = t.final_account_code
      ? `${t.final_account_code} - ${t.final_category ?? category}`
      : (t.suggested_account_code
          ? `${t.suggested_account_code} - ${category}`
          : 'Uncategorized')
    // QuickBooks: debits are negative, credits are positive
    const amount = t.type === 'debit' ? -t.amount : t.amount

    return {
      Date:        t.date,
      Account:     account,
      Description: t.description,
      Amount:      amount.toFixed(2),
      Category:    category,
      Class:       clientName,
    }
  })

  const csv = Papa.unparse(rows, { header: true })
  return csv + '\n\n"Generated by CloseBooks — AI-Powered Month-End Close — closebooks-app.vercel.app"'
}

// ---------------------------------------------------------------------------
// Standard CSV
// Columns: Date, Description, Category, Account Code, Debit, Credit, Status, Notes
// Debit and Credit are split into separate columns (never both populated).
// ---------------------------------------------------------------------------
function buildStandardCSV(transactions: Transaction[]): string {
  const rows = transactions.map((t) => {
    const category    = t.final_category    ?? t.suggested_category    ?? ''
    const accountCode = t.final_account_code ?? t.suggested_account_code ?? ''

    return {
      Date:           t.date,
      Description:    t.description,
      Category:       category,
      'Account Code': accountCode,
      Debit:          t.type === 'debit'  ? t.amount.toFixed(2) : '',
      Credit:         t.type === 'credit' ? t.amount.toFixed(2) : '',
      Status:         t.status,
      Notes:          t.notes ?? '',
    }
  })

  const csv = Papa.unparse(rows, { header: true })
  return csv + '\n\n"Generated by CloseBooks — AI-Powered Month-End Close — closebooks-app.vercel.app"'
}

// ---------------------------------------------------------------------------
// Route handler
// ---------------------------------------------------------------------------
export async function POST(request: NextRequest) {
  const access = await requireRouteAccess(request)
  if (!access.ok) return access.response

  let body: unknown
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON in request body.' }, { status: 400 })
  }

  if (!isValidBody(body)) {
    return NextResponse.json(
      { error: 'Request body must include transactions (array), chartOfAccounts (array), clientName (string), and format ("quickbooks" or "standard").' },
      { status: 422 }
    )
  }

  const { transactions, chartOfAccounts, clientName, format } = body

  if (transactions.length === 0) {
    return NextResponse.json({ error: 'No transactions to export.' }, { status: 422 })
  }

  if (chartOfAccounts.length === 0) {
    return NextResponse.json({ error: 'Chart of accounts is required for export validation.' }, { status: 422 })
  }

  const validation = validateTransactionsForExport(transactions, chartOfAccounts)
  if (!validation.ok) {
    return NextResponse.json(
      {
        error: 'Resolve export validation issues before downloading accounting output.',
        issues: validation.issues,
      },
      { status: 422 }
    )
  }

  const base      = safeFilename(clientName)
  const datestamp = new Date().toISOString().slice(0, 10)
  const filename  = `${base}_close_${datestamp}.csv`

  const csv = format === 'quickbooks'
    ? buildQuickBooksCSV(transactions, clientName, chartOfAccounts)
    : buildStandardCSV(transactions.map((tx) => canonicalizeTransactionForExport(tx, chartOfAccounts)))

  return new NextResponse(csv, {
    status: 200,
    headers: {
      'Content-Type':        'text/csv; charset=utf-8',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'X-Transaction-Count': String(transactions.length),
    },
  })
}
