import type { Transaction, ChartOfAccounts } from '@/types'

// ─────────────────────────────────────────────────────────────────────────────
// Chart of Accounts — Standard Small Business
// ─────────────────────────────────────────────────────────────────────────────

export const DEMO_COA: ChartOfAccounts[] = [
  // Assets
  { code: '1010', name: 'Checking Account',          type: 'asset'    },
  { code: '1020', name: 'Savings Account',            type: 'asset'    },
  { code: '1100', name: 'Accounts Receivable',        type: 'asset'    },
  { code: '1200', name: 'Prepaid Expenses',           type: 'asset'    },
  { code: '1500', name: 'Fixed Assets',               type: 'asset'    },

  // Liabilities
  { code: '2010', name: 'Accounts Payable',           type: 'liability' },
  { code: '2100', name: 'Credit Card Payable',        type: 'liability' },
  { code: '2200', name: 'Payroll Liabilities',        type: 'liability' },
  { code: '2300', name: 'Sales Tax Payable',          type: 'liability' },

  // Equity
  { code: '3010', name: 'Owner\'s Equity',            type: 'equity'   },
  { code: '3100', name: 'Retained Earnings',          type: 'equity'   },

  // Revenue
  { code: '4010', name: 'Service Revenue',            type: 'revenue'  },
  { code: '4020', name: 'Consulting Revenue',         type: 'revenue'  },
  { code: '4120', name: 'Interest Income',            type: 'revenue'  },
  { code: '4200', name: 'Other Income',               type: 'revenue'  },

  // Expenses
  { code: '6010', name: 'Payroll & Wages',            type: 'expense'  },
  { code: '6020', name: 'Payroll Tax Expense',        type: 'expense'  },
  { code: '6100', name: 'Rent & Occupancy',           type: 'expense'  },
  { code: '6110', name: 'Utilities',                  type: 'expense'  },
  { code: '6120', name: 'Internet & Phone',           type: 'expense'  },
  { code: '6200', name: 'Office Supplies',            type: 'expense'  },
  { code: '6210', name: 'Meals & Entertainment',      type: 'expense'  },
  { code: '6220', name: 'Software & SaaS',            type: 'expense'  },
  { code: '6300', name: 'Travel & Transportation',    type: 'expense'  },
  { code: '6310', name: 'Advertising & Marketing',    type: 'expense'  },
  { code: '6400', name: 'Professional Services',      type: 'expense'  },
  { code: '6410', name: 'Insurance',                  type: 'expense'  },
  { code: '6500', name: 'Bank & Merchant Fees',       type: 'expense'  },
  { code: '6900', name: 'Miscellaneous Expense',      type: 'expense'  },
]

// ─────────────────────────────────────────────────────────────────────────────
// 20 realistic demo transactions — March 2026, "Sunrise Advisory LLC"
// ─────────────────────────────────────────────────────────────────────────────

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id:                    'demo-001',
    date:                  '2026-03-31',
    description:           'GUSTO PAYROLL MAR 16-31',
    original_description:  'GUSTO PAYROLL MAR 16-31',
    amount:                14250.00,
    type:                  'debit',
    suggested_category:    'Payroll & Wages',
    suggested_account_code: '6010',
    confidence:            0.99,
    status:                'approved',
    final_category:        'Payroll & Wages',
    final_account_code:    '6010',
  },
  {
    id:                    'demo-002',
    date:                  '2026-03-29',
    description:           'DEPOSIT - CLIENT PMT ACME CORP INV-2089',
    original_description:  'DEPOSIT - CLIENT PMT ACME CORP INV-2089',
    amount:                8500.00,
    type:                  'credit',
    suggested_category:    'Service Revenue',
    suggested_account_code: '4010',
    confidence:            0.97,
    status:                'approved',
    final_category:        'Service Revenue',
    final_account_code:    '4010',
  },
  {
    id:                    'demo-003',
    date:                  '2026-03-28',
    description:           'CHECK #1042 - OFFICE RENT MARCH',
    original_description:  'CHECK #1042 - OFFICE RENT MARCH',
    amount:                3200.00,
    type:                  'debit',
    suggested_category:    'Rent & Occupancy',
    suggested_account_code: '6100',
    confidence:            0.98,
    status:                'approved',
    final_category:        'Rent & Occupancy',
    final_account_code:    '6100',
  },
  {
    id:                    'demo-004',
    date:                  '2026-03-28',
    description:           'COMCAST BUSINESS INTERNET',
    original_description:  'COMCAST BUSINESS INTERNET 312-555-0181',
    amount:                189.99,
    type:                  'debit',
    suggested_category:    'Internet & Phone',
    suggested_account_code: '6120',
    confidence:            0.96,
    status:                'approved',
    final_category:        'Internet & Phone',
    final_account_code:    '6120',
  },
  {
    id:                    'demo-005',
    date:                  '2026-03-27',
    description:           'DEPOSIT - CLIENT PMT RIVERDALE GROUP INV-2090',
    original_description:  'DEPOSIT - CLIENT PMT RIVERDALE GROUP INV-2090',
    amount:                12000.00,
    type:                  'credit',
    suggested_category:    'Consulting Revenue',
    suggested_account_code: '4020',
    confidence:            0.95,
    status:                'approved',
    final_category:        'Consulting Revenue',
    final_account_code:    '4020',
  },
  {
    id:                    'demo-006',
    date:                  '2026-03-26',
    description:           'AMAZON WEB SERVICES',
    original_description:  'AMAZON WEB SERVICES AWS.AMAZON.COM',
    amount:                847.23,
    type:                  'debit',
    suggested_category:    'Software & SaaS',
    suggested_account_code: '6220',
    confidence:            0.93,
    status:                'approved',
    final_category:        'Software & SaaS',
    final_account_code:    '6220',
  },
  {
    id:                    'demo-007',
    date:                  '2026-03-25',
    description:           'GUSTO PAYROLL MAR 1-15',
    original_description:  'GUSTO PAYROLL MAR 1-15',
    amount:                14250.00,
    type:                  'debit',
    suggested_category:    'Payroll & Wages',
    suggested_account_code: '6010',
    confidence:            0.99,
    status:                'approved',
    final_category:        'Payroll & Wages',
    final_account_code:    '6010',
  },
  {
    id:                    'demo-008',
    date:                  '2026-03-24',
    description:           'NOTION.SO MONTHLY',
    original_description:  'NOTION.SO MONTHLY SUBSCRIPTION',
    amount:                96.00,
    type:                  'debit',
    suggested_category:    'Software & SaaS',
    suggested_account_code: '6220',
    confidence:            0.94,
    status:                'approved',
    final_category:        'Software & SaaS',
    final_account_code:    '6220',
  },
  {
    id:                    'demo-009',
    date:                  '2026-03-22',
    description:           'UNITED AIRLINES 0162441892304',
    original_description:  'UNITED AIRLINES 0162441892304',
    amount:                612.40,
    type:                  'debit',
    suggested_category:    'Travel & Transportation',
    suggested_account_code: '6300',
    confidence:            0.91,
    status:                'approved',
    final_category:        'Travel & Transportation',
    final_account_code:    '6300',
  },
  {
    id:                    'demo-010',
    date:                  '2026-03-21',
    description:           'GOOGLE WORKSPACE',
    original_description:  'GOOGLE *WORKSPACE GOOGLE.COM/CH',
    amount:                144.00,
    type:                  'debit',
    suggested_category:    'Software & SaaS',
    suggested_account_code: '6220',
    confidence:            0.97,
    status:                'approved',
    final_category:        'Software & SaaS',
    final_account_code:    '6220',
  },
  {
    id:                    'demo-011',
    date:                  '2026-03-20',
    description:           'STAPLES #1184 OFFICE SUPPLIES',
    original_description:  'STAPLES #1184 CHICAGO IL',
    amount:                234.17,
    type:                  'debit',
    suggested_category:    'Office Supplies',
    suggested_account_code: '6200',
    confidence:            0.88,
    status:                'approved',
    final_category:        'Office Supplies',
    final_account_code:    '6200',
  },
  {
    id:                    'demo-012',
    date:                  '2026-03-19',
    description:           'INTEREST INCOME',
    original_description:  'INTEREST EARNED ON DEPOSIT',
    amount:                41.83,
    type:                  'credit',
    suggested_category:    'Interest Income',
    suggested_account_code: '4120',
    confidence:            0.99,
    status:                'approved',
    final_category:        'Interest Income',
    final_account_code:    '4120',
  },
  {
    id:                    'demo-013',
    date:                  '2026-03-18',
    description:           'LINKEDIN PREMIUM BUSINESS',
    original_description:  'LINKEDIN *PREMIUM LINKEDIN.COM',
    amount:                59.99,
    type:                  'debit',
    suggested_category:    'Advertising & Marketing',
    suggested_account_code: '6310',
    confidence:            0.82,
    status:                'approved',
    final_category:        'Advertising & Marketing',
    final_account_code:    '6310',
  },
  {
    id:                    'demo-014',
    date:                  '2026-03-17',
    description:           'PROGRESSIVE INSURANCE',
    original_description:  'PROGRESSIVE INSURANCE 800-776-4737',
    amount:                487.00,
    type:                  'debit',
    suggested_category:    'Insurance',
    suggested_account_code: '6410',
    confidence:            0.95,
    status:                'approved',
    final_category:        'Insurance',
    final_account_code:    '6410',
  },
  {
    id:                    'demo-015',
    date:                  '2026-03-15',
    description:           'RESTAURANT - CLIENT DINNER',
    original_description:  'GIBSONS BAR AND STEAKHOUSE CHICAGO IL',
    amount:                312.80,
    type:                  'debit',
    suggested_category:    'Meals & Entertainment',
    suggested_account_code: '6210',
    confidence:            0.79,
    status:                'pending',
  },
  {
    id:                    'demo-016',
    date:                  '2026-03-14',
    description:           'DEPOSIT - WIRE TRANSFER',
    original_description:  'INCOMING WIRE TRANSFER REF#881204',
    amount:                25000.00,
    type:                  'credit',
    suggested_category:    'Service Revenue',
    suggested_account_code: '4010',
    confidence:            0.76,
    status:                'pending',
  },
  {
    id:                    'demo-017',
    date:                  '2026-03-12',
    description:           'STRIPE PAYOUT',
    original_description:  'STRIPE PAYOUT ST-1A2B3C4D5E6F',
    amount:                6340.00,
    type:                  'credit',
    suggested_category:    'Service Revenue',
    suggested_account_code: '4010',
    confidence:            0.85,
    status:                'approved',
    final_category:        'Service Revenue',
    final_account_code:    '4010',
  },
  {
    id:                    'demo-018',
    date:                  '2026-03-10',
    description:           'CHASE BANK SERVICE FEE',
    original_description:  'MONTHLY SERVICE FEE',
    amount:                25.00,
    type:                  'debit',
    suggested_category:    'Bank & Merchant Fees',
    suggested_account_code: '6500',
    confidence:            0.98,
    status:                'approved',
    final_category:        'Bank & Merchant Fees',
    final_account_code:    '6500',
  },
  {
    id:                    'demo-019',
    date:                  '2026-03-08',
    description:           'UBER TRIP',
    original_description:  'UBER *TRIP 800-592-8996 CA',
    amount:                34.50,
    type:                  'debit',
    suggested_category:    'Travel & Transportation',
    suggested_account_code: '6300',
    confidence:            0.87,
    status:                'approved',
    final_category:        'Travel & Transportation',
    final_account_code:    '6300',
  },
  {
    id:                    'demo-020',
    date:                  '2026-03-05',
    description:           'TRANSFER - UNKNOWN ORIGIN',
    original_description:  'ACH DEBIT 021000089 MISC PMT',
    amount:                1850.00,
    type:                  'debit',
    suggested_category:    'Miscellaneous Expense',
    suggested_account_code: '6900',
    confidence:            0.38,
    status:                'flagged',
  },
]

// Derived summary counts (for header display)
export const DEMO_SUMMARY = {
  clientName:        'Sunrise Advisory LLC',
  period:            'March 2026',
  total:             DEMO_TRANSACTIONS.length,
  approved:          DEMO_TRANSACTIONS.filter((t) => t.status === 'approved' || t.status === 'edited').length,
  pending:           DEMO_TRANSACTIONS.filter((t) => t.status === 'pending').length,
  flagged:           DEMO_TRANSACTIONS.filter((t) => t.status === 'flagged').length,
  autoApproved:      DEMO_TRANSACTIONS.filter((t) => t.status === 'approved' && t.confidence >= 0.85).length,
}
