export interface Firm {
  id: string
  slug: string
  name: string
  tagline: string
  city: string
  state: string
  foundedYear: number
  teamSize: string
  specialties: string[]
  services: string[]
  hourlyRateMin: number
  hourlyRateMax: number
  bio: string
  closesCompleted: number
  avgCloseTimeMin: number
  accuracyRate: number
  clientSatisfaction: number
  verified: boolean
  reviews: {
    author: string
    company: string
    rating: number
    text: string
    date: string
  }[]
}

export const INDUSTRIES = [
  'Construction',
  'SaaS',
  'Restaurant',
  'Real Estate',
  'Healthcare',
  'Manufacturing',
  'Retail',
  'Nonprofit',
  'Legal',
  'E-Commerce',
  'Hospitality',
  'Transportation',
  'Professional Services',
]

export const SERVICES = [
  'Bookkeeping',
  'Tax Prep',
  'Audit',
  'Advisory',
  'Payroll',
  '1099 Filing',
]

export const DEMO_FIRMS: Firm[] = [
  {
    id: '1',
    slug: 'meridian-cpa-group',
    name: 'Meridian CPA Group',
    tagline: 'Precision books for complex industries.',
    city: 'Atlanta',
    state: 'GA',
    foundedYear: 2011,
    teamSize: '10–25',
    specialties: ['Construction', 'Real Estate', 'Manufacturing'],
    services: ['Bookkeeping', 'Tax Prep', 'Advisory', 'Payroll'],
    hourlyRateMin: 150,
    hourlyRateMax: 300,
    bio: 'Meridian CPA Group has served Atlanta-area businesses since 2011, specializing in construction and real estate firms. We combine deep industry knowledge with AI-powered close processes to deliver books you can trust — fast.',
    closesCompleted: 1203,
    avgCloseTimeMin: 31,
    accuracyRate: 99.3,
    clientSatisfaction: 4.9,
    verified: true,
    reviews: [
      { author: 'David Harmon', company: 'Harmon Build Co.', rating: 5, text: 'Meridian cut our close from 3 weeks to 2 days. The accuracy is unreal — we haven\'t had a reconciliation issue in 8 months.', date: '2025-11-14' },
      { author: 'Sara Patel', company: 'Patel Real Estate Holdings', rating: 5, text: 'Finally a CPA firm that understands real estate nuances. Their job-cost reporting is exactly what we needed.', date: '2025-10-02' },
      { author: 'James Whitfield', company: 'Whitfield Manufacturing', rating: 5, text: 'Responsive, accurate, and proactive with tax savings advice. Couldn\'t ask for more.', date: '2025-09-18' },
    ],
  },
  {
    id: '2',
    slug: 'pinecrest-advisors',
    name: 'Pinecrest Advisors',
    tagline: 'SaaS-focused accounting built for growth.',
    city: 'Austin',
    state: 'TX',
    foundedYear: 2016,
    teamSize: '5–10',
    specialties: ['SaaS', 'E-Commerce', 'Professional Services'],
    services: ['Bookkeeping', 'Tax Prep', 'Advisory', '1099 Filing'],
    hourlyRateMin: 175,
    hourlyRateMax: 350,
    bio: 'We live and breathe SaaS metrics — ARR, churn, LTV. Pinecrest Advisors helps fast-growing software companies keep clean books while their teams focus on product.',
    closesCompleted: 847,
    avgCloseTimeMin: 34,
    accuracyRate: 99.1,
    clientSatisfaction: 4.9,
    verified: true,
    reviews: [
      { author: 'Mia Torres', company: 'Launchpad SaaS', rating: 5, text: 'Pinecrest understands our revenue recognition challenges better than any accountant we\'ve worked with.', date: '2025-12-01' },
      { author: 'Kevin Park', company: 'ShopScale', rating: 5, text: 'They integrated directly with Stripe and Shopify. Our books are always clean without any manual work on our end.', date: '2025-11-10' },
      { author: 'Rachel Lin', company: 'Draftboard Inc.', rating: 4, text: 'Great communication and fast turnarounds. Would love a dedicated account manager.', date: '2025-10-22' },
    ],
  },
  {
    id: '3',
    slug: 'harbor-financial-group',
    name: 'Harbor Financial Group',
    tagline: 'Restaurant and hospitality accounting, perfected.',
    city: 'Chicago',
    state: 'IL',
    foundedYear: 2009,
    teamSize: '25–50',
    specialties: ['Restaurant', 'Hospitality', 'Retail'],
    services: ['Bookkeeping', 'Tax Prep', 'Payroll', 'Advisory', 'Audit'],
    hourlyRateMin: 125,
    hourlyRateMax: 275,
    bio: 'Harbor Financial Group has served the Chicago hospitality scene for over 15 years. We understand tip credits, variable staffing, and food cost accounting — things generalist CPAs miss.',
    closesCompleted: 2104,
    avgCloseTimeMin: 28,
    accuracyRate: 98.8,
    clientSatisfaction: 4.8,
    verified: true,
    reviews: [
      { author: 'Tony Greco', company: 'Greco\'s Kitchen Group', rating: 5, text: 'Harbor handles payroll for 6 of our locations. It\'s completely seamless now.', date: '2025-12-10' },
      { author: 'Alicia Drummond', company: 'The Drummond Hotel', rating: 5, text: 'Finally found a firm that truly gets hospitality accounting. Saved us $40k in tax liability last year.', date: '2025-10-14' },
      { author: 'Marco Ricci', company: 'Ricci\'s Trattoria', rating: 4, text: 'Reliable, responsive, and they actually understand restaurant P&L. Very happy.', date: '2025-09-05' },
    ],
  },
  {
    id: '4',
    slug: 'summit-tax-solutions',
    name: 'Summit Tax Solutions',
    tagline: 'Healthcare and nonprofit accounting specialists.',
    city: 'Denver',
    state: 'CO',
    foundedYear: 2014,
    teamSize: '5–10',
    specialties: ['Healthcare', 'Nonprofit', 'Legal'],
    services: ['Bookkeeping', 'Tax Prep', 'Audit', '1099 Filing'],
    hourlyRateMin: 140,
    hourlyRateMax: 280,
    bio: 'Summit Tax Solutions focuses exclusively on healthcare providers and nonprofits. We navigate the complex compliance and grant-tracking needs that these sectors demand, with 99%+ accuracy on every close.',
    closesCompleted: 634,
    avgCloseTimeMin: 38,
    accuracyRate: 99.0,
    clientSatisfaction: 4.8,
    verified: true,
    reviews: [
      { author: 'Dr. Nancy Webb', company: 'Webb Family Clinic', rating: 5, text: 'Summit understands HIPAA-compliant accounting and grant compliance. Exactly what we needed.', date: '2025-11-28' },
      { author: 'Robert Campos', company: 'Denver Arts Alliance', rating: 5, text: 'Grant tracking and nonprofit fund accounting are their bread and butter. We couldn\'t run our org without them.', date: '2025-10-30' },
      { author: 'Patricia Moore', company: 'Sunrise Pediatrics', rating: 4, text: 'Very thorough and always available for questions. Our closes are consistently on time.', date: '2025-09-15' },
    ],
  },
  {
    id: '5',
    slug: 'clearview-cpa',
    name: 'Clearview CPA',
    tagline: 'Transparent books for transparent businesses.',
    city: 'Seattle',
    state: 'WA',
    foundedYear: 2018,
    teamSize: '2–5',
    specialties: ['E-Commerce', 'SaaS', 'Professional Services'],
    services: ['Bookkeeping', 'Tax Prep', 'Advisory'],
    hourlyRateMin: 160,
    hourlyRateMax: 320,
    bio: 'Clearview CPA is a boutique firm serving Pacific Northwest tech and e-commerce businesses. Small team, senior-level attention on every account.',
    closesCompleted: 412,
    avgCloseTimeMin: 41,
    accuracyRate: 98.9,
    clientSatisfaction: 5.0,
    verified: true,
    reviews: [
      { author: 'Yuki Tanaka', company: 'Tanaka Studio', rating: 5, text: 'Incredible attention to detail. I always feel like my business is their only client.', date: '2025-12-05' },
      { author: 'Ben Gallagher', company: 'Pinewave Commerce', rating: 5, text: 'They spotted a $12k over-payment to a vendor and caught it before we filed. That alone paid for a year of service.', date: '2025-11-17' },
      { author: 'Chloe Andersen', company: 'Andersen Consulting', rating: 5, text: 'Best CPA experience I\'ve had in 10 years of running a business. Highly recommend.', date: '2025-10-08' },
    ],
  },
  {
    id: '6',
    slug: 'ironclad-accounting',
    name: 'Ironclad Accounting',
    tagline: 'Built for the trades — construction to manufacturing.',
    city: 'Phoenix',
    state: 'AZ',
    foundedYear: 2007,
    teamSize: '10–25',
    specialties: ['Construction', 'Manufacturing', 'Transportation'],
    services: ['Bookkeeping', 'Tax Prep', 'Payroll', 'Audit', 'Advisory'],
    hourlyRateMin: 120,
    hourlyRateMax: 250,
    bio: 'Ironclad Accounting has been the go-to firm for Southwest contractors and manufacturers for nearly two decades. Job-cost accounting, equipment depreciation, and multi-entity structures are our specialty.',
    closesCompleted: 3210,
    avgCloseTimeMin: 26,
    accuracyRate: 98.7,
    clientSatisfaction: 4.8,
    verified: true,
    reviews: [
      { author: 'Mike Dolan', company: 'Dolan Excavation LLC', rating: 5, text: 'They understand job costing like no one else. Our project profitability reports are actually useful now.', date: '2025-12-12' },
      { author: 'Sandra Ruiz', company: 'Ruiz Transport', rating: 5, text: 'Ironclad handles our 47 drivers\' payroll without a hitch. No complaints.', date: '2025-11-03' },
      { author: 'Chris Brewer', company: 'Desert Steel Works', rating: 4, text: 'Solid firm with deep trades experience. Very reliable.', date: '2025-09-22' },
    ],
  },
  {
    id: '7',
    slug: 'grove-street-financial',
    name: 'Grove Street Financial',
    tagline: 'Real estate accounting for serious investors.',
    city: 'Miami',
    state: 'FL',
    foundedYear: 2015,
    teamSize: '5–10',
    specialties: ['Real Estate', 'Construction', 'Hospitality'],
    services: ['Bookkeeping', 'Tax Prep', 'Advisory', '1099 Filing'],
    hourlyRateMin: 155,
    hourlyRateMax: 300,
    bio: 'Grove Street Financial serves Florida\'s most active real estate investors and developers. From single-family flips to 200-unit multifamily developments, we\'ve seen it all and can handle it all.',
    closesCompleted: 891,
    avgCloseTimeMin: 33,
    accuracyRate: 99.2,
    clientSatisfaction: 4.9,
    verified: true,
    reviews: [
      { author: 'Diane Ferrara', company: 'Ferrara Holdings', rating: 5, text: 'They manage 14 entities for us. Organization, accuracy, communication — everything is excellent.', date: '2025-12-08' },
      { author: 'Marcus Webb', company: 'SunCoast Developments', rating: 5, text: 'Depreciation schedules and cost-seg studies are handled flawlessly. Worth every dollar.', date: '2025-11-20' },
      { author: 'Natalie Kim', company: 'NKB Properties', rating: 5, text: 'Best real estate CPA firm in Miami, no contest.', date: '2025-10-11' },
    ],
  },
  {
    id: '8',
    slug: 'compass-cpa-partners',
    name: 'Compass CPA Partners',
    tagline: 'Full-service accounting for Main Street businesses.',
    city: 'Nashville',
    state: 'TN',
    foundedYear: 2012,
    teamSize: '10–25',
    specialties: ['Retail', 'Restaurant', 'Professional Services'],
    services: ['Bookkeeping', 'Tax Prep', 'Payroll', 'Advisory', '1099 Filing'],
    hourlyRateMin: 110,
    hourlyRateMax: 230,
    bio: 'Compass CPA Partners brings big-firm expertise to small and mid-sized Nashville businesses. We\'re approachable, proactive, and genuinely invested in our clients\' success.',
    closesCompleted: 1567,
    avgCloseTimeMin: 29,
    accuracyRate: 98.6,
    clientSatisfaction: 4.8,
    verified: true,
    reviews: [
      { author: 'Amber Cole', company: 'Cole Boutique', rating: 5, text: 'Compass helped us clean up 2 years of bookkeeping chaos in under a month. Life-changing.', date: '2025-12-03' },
      { author: 'Jordan Maxwell', company: 'Maxwell Law Group', rating: 5, text: 'Finally a CPA that explains things in plain English. IOLTA trust accounting done right.', date: '2025-10-29' },
      { author: 'Tiffany Nguyen', company: 'Saigon Kitchen', rating: 4, text: 'Very responsive and affordable. Great for a small restaurant owner like me.', date: '2025-09-10' },
    ],
  },
  {
    id: '9',
    slug: 'axiom-financial-services',
    name: 'Axiom Financial Services',
    tagline: 'Enterprise-grade accounting for growth-stage companies.',
    city: 'New York',
    state: 'NY',
    foundedYear: 2010,
    teamSize: '25–50',
    specialties: ['SaaS', 'E-Commerce', 'Manufacturing'],
    services: ['Bookkeeping', 'Tax Prep', 'Audit', 'Advisory', 'Payroll', '1099 Filing'],
    hourlyRateMin: 200,
    hourlyRateMax: 500,
    bio: 'Axiom Financial Services has served growth-stage and enterprise clients across the Northeast for 15 years. Audit-ready books, complex revenue recognition, and M&A readiness are our calling card.',
    closesCompleted: 4102,
    avgCloseTimeMin: 24,
    accuracyRate: 99.4,
    clientSatisfaction: 4.9,
    verified: true,
    reviews: [
      { author: 'Derek Chu', company: 'NovaSoft Inc.', rating: 5, text: 'Axiom had us audit-ready in 60 days. Incredible team, top-tier work.', date: '2025-12-15' },
      { author: 'Priya Mehta', company: 'Mehta Manufacturing', rating: 5, text: 'Complex cost accounting across 3 plants — handled without a single error. Remarkable.', date: '2025-11-07' },
      { author: 'Liam O\'Brien', company: 'O\'Brien Commerce', rating: 5, text: 'They scaled with us from $2M to $18M in revenue. Always one step ahead.', date: '2025-10-16' },
    ],
  },
  {
    id: '10',
    slug: 'redwood-accounting',
    name: 'Redwood Accounting',
    tagline: 'Sustainable businesses deserve sustainable books.',
    city: 'Portland',
    state: 'OR',
    foundedYear: 2017,
    teamSize: '2–5',
    specialties: ['Nonprofit', 'E-Commerce', 'Professional Services'],
    services: ['Bookkeeping', 'Tax Prep', 'Advisory', '1099 Filing'],
    hourlyRateMin: 130,
    hourlyRateMax: 260,
    bio: 'Redwood Accounting serves mission-driven organizations and impact-focused businesses. We believe clean books are the foundation of every successful cause.',
    closesCompleted: 298,
    avgCloseTimeMin: 44,
    accuracyRate: 98.5,
    clientSatisfaction: 4.8,
    verified: true,
    reviews: [
      { author: 'Grace Hoffman', company: 'Green Futures Fund', rating: 5, text: 'Redwood gets the nonprofit world. Grant compliance is never a headache with them.', date: '2025-11-25' },
      { author: 'Sam Foster', company: 'Foster Organics', rating: 5, text: 'Warm, knowledgeable, and they genuinely care about our mission.', date: '2025-10-18' },
      { author: 'Isabel Cruz', company: 'Cruz Design Studio', rating: 5, text: 'Quarterly financial reviews with Redwood have completely changed how I run my business.', date: '2025-09-12' },
    ],
  },
  {
    id: '11',
    slug: 'keystone-cpa-advisors',
    name: 'Keystone CPA Advisors',
    tagline: 'Healthcare and professional services accounting.',
    city: 'Philadelphia',
    state: 'PA',
    foundedYear: 2013,
    teamSize: '10–25',
    specialties: ['Healthcare', 'Legal', 'Professional Services'],
    services: ['Bookkeeping', 'Tax Prep', 'Audit', 'Payroll', 'Advisory'],
    hourlyRateMin: 145,
    hourlyRateMax: 290,
    bio: 'Keystone CPA Advisors brings specialized expertise to healthcare practices and professional service firms throughout the Mid-Atlantic region. We\'re proud of our 99%+ close accuracy across 900+ engagements.',
    closesCompleted: 923,
    avgCloseTimeMin: 36,
    accuracyRate: 99.0,
    clientSatisfaction: 4.9,
    verified: true,
    reviews: [
      { author: 'Dr. Alex Kim', company: 'Kim Orthopedics', rating: 5, text: 'Keystone handles all five of our physician practice locations. Billing reconciliation has never been easier.', date: '2025-12-09' },
      { author: 'Margaret Stone', company: 'Stone & Partners LLP', rating: 5, text: 'IOLTA compliance and partner distributions — all handled precisely and confidentially.', date: '2025-11-01' },
      { author: 'Frank Deluca', company: 'DeLuca Dental Group', rating: 4, text: 'Excellent service and always available for questions. Highly professional team.', date: '2025-09-28' },
    ],
  },
  {
    id: '12',
    slug: 'pacific-rim-financial',
    name: 'Pacific Rim Financial',
    tagline: 'Tech and logistics accounting for the modern economy.',
    city: 'San Francisco',
    state: 'CA',
    foundedYear: 2019,
    teamSize: '5–10',
    specialties: ['SaaS', 'Transportation', 'E-Commerce'],
    services: ['Bookkeeping', 'Tax Prep', 'Advisory', '1099 Filing'],
    hourlyRateMin: 200,
    hourlyRateMax: 450,
    bio: 'Pacific Rim Financial was born in the Bay Area tech ecosystem. We speak the language of ARR, burn rate, and runway — and deliver books that satisfy your investors and your auditors.',
    closesCompleted: 511,
    avgCloseTimeMin: 32,
    accuracyRate: 99.2,
    clientSatisfaction: 4.9,
    verified: true,
    reviews: [
      { author: 'Ethan Zhao', company: 'Shipline Technologies', rating: 5, text: 'Pacific Rim built our financial model from scratch and keeps our books clean for investors. Essential partner.', date: '2025-12-11' },
      { author: 'Sophia Reyes', company: 'Reyes Logistics', rating: 5, text: 'Fleet accounting, driver 1099s, IFTA filings — they handle it all without a single complaint.', date: '2025-11-15' },
      { author: 'Daniel Fong', company: 'Fong Cloud', rating: 5, text: 'Series A audit was a breeze because Pacific Rim had kept our books immaculate all year.', date: '2025-10-04' },
    ],
  },
]
