import type { RegulatoryAlert } from '@/types/compliance'

export const REGULATORY_ALERTS: RegulatoryAlert[] = [
  {
    id: 'irs-2024-01',
    title: 'IRS Increases Standard Mileage Rate to 67 Cents Per Mile',
    summary: 'The IRS announced the 2024 standard mileage rate for business driving is 67 cents per mile, up from 65.5 cents.',
    fullText: 'Starting January 1, 2024, the standard mileage rate for business travel has increased to 67 cents per mile. This rate applies to all business miles driven and should be used when computing deductible costs of operating a vehicle for business purposes. Employers may also use this rate to reimburse employees for business mileage.',
    effectiveDate: '2024-01-01',
    publishedDate: '2023-12-14',
    severity: 'important',
    source: 'IRS',
    affectedIndustries: [],
    affectedStates: [],
    tags: ['mileage', 'vehicles', 'deductions', 'reimbursement'],
    actionRequired: 'Update mileage reimbursement policies and ensure clients use 67¢/mile for 2024 returns.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nThe IRS has updated the standard mileage rate for 2024 to 67 cents per mile (up from 65.5 cents). If you use a vehicle for business purposes, please ensure your mileage logs reflect this updated rate.\n\nAction Required: Update your vehicle expense tracking to use the new rate effective January 1, 2024.\n\nPlease contact us if you have any questions.\n\nWarm regards,\n[FIRM_NAME]',
    url: 'https://www.irs.gov/newsroom/irs-issues-standard-mileage-rates-for-2024',
  },
  {
    id: 'irs-1099k-2024',
    title: '1099-K Reporting Threshold: $5,000 for 2024 Tax Year',
    summary: 'IRS sets $5,000 threshold for 2024 Form 1099-K reporting from payment platforms like PayPal, Venmo, Square.',
    fullText: 'For the 2024 tax year, third-party settlement organizations (PayPal, Venmo, Square, Stripe, etc.) must issue 1099-K forms to recipients who receive more than $5,000 in payments. This is a transitional threshold as the IRS moves toward the eventual $600 threshold mandated by the American Rescue Plan Act.',
    effectiveDate: '2024-01-01',
    publishedDate: '2023-11-21',
    severity: 'critical',
    source: 'IRS',
    affectedIndustries: ['Restaurant', 'Retail', 'E-commerce', 'Professional Services'],
    affectedStates: [],
    tags: ['1099-K', 'payment platforms', 'gig economy', 'reporting'],
    actionRequired: 'Alert clients receiving payments via PayPal/Venmo/Square to expect 1099-K forms if over $5,000.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nImportant update regarding 1099-K tax reporting: The IRS has set a $5,000 threshold for 2024. If you receive payments through platforms like PayPal, Venmo, Cash App, or Square, you will receive a Form 1099-K if your total receipts exceed $5,000.\n\nAction Required: Please save all 1099-K forms you receive and forward them to our office. Do not discard these forms — they must be reported on your tax return.\n\nContact us with any questions.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'irs-retirement-2024',
    title: '2024 Retirement Contribution Limits Increased',
    summary: '401(k) limit rises to $23,000; IRA limit rises to $7,000; catch-up contributions unchanged.',
    fullText: 'The IRS has announced cost-of-living adjustments for 2024 retirement account contribution limits. The 401(k), 403(b), and most 457 plan elective deferral limit increases to $23,000. The IRA contribution limit increases to $7,000 (up from $6,500). The catch-up contribution limit for 401(k) participants 50 and over remains $7,500. The SIMPLE IRA limit increases to $16,000.',
    effectiveDate: '2024-01-01',
    publishedDate: '2023-11-01',
    severity: 'important',
    source: 'IRS',
    affectedIndustries: [],
    affectedStates: [],
    tags: ['retirement', '401k', 'IRA', 'contributions', 'SIMPLE'],
    actionRequired: 'Advise clients to maximize retirement contributions under new limits.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nGood news: retirement contribution limits have increased for 2024.\n\n• 401(k)/403(b): $23,000 (up $500)\n• IRA (Traditional or Roth): $7,000 (up $500)\n• Catch-up contributions (age 50+): +$7,500 for 401(k), +$1,000 for IRA\n\nAction Required: Consider increasing your retirement contributions to take full advantage of these higher limits and reduce your taxable income.\n\nLet us know if you would like to discuss retirement planning strategies.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'dol-overtime-2024',
    title: 'DOL Raises Overtime Salary Threshold to $43,888',
    summary: 'New DOL rule effective July 1, 2024 raises salary threshold for overtime exemption from $35,568 to $43,888.',
    fullText: 'The Department of Labor finalized a rule increasing the salary threshold for the Fair Labor Standards Act (FLSA) white-collar overtime exemptions. Effective July 1, 2024, the threshold rises to $43,888/year ($844/week). A second increase to $58,656/year takes effect January 1, 2025. Employees earning below these thresholds must receive overtime pay for hours over 40/week, regardless of job title.',
    effectiveDate: '2024-07-01',
    publishedDate: '2024-04-23',
    severity: 'critical',
    source: 'DOL',
    affectedIndustries: [],
    affectedStates: [],
    employeeMin: 1,
    tags: ['overtime', 'FLSA', 'salary threshold', 'payroll', 'employees'],
    actionRequired: 'Audit client payroll — reclassify employees earning under $43,888 or raise their salaries.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nUrgent payroll compliance alert: The Department of Labor has raised the overtime salary threshold.\n\nEffective July 1, 2024: Any employee classified as exempt from overtime must earn at least $43,888/year ($844/week).\nEffective January 1, 2025: This threshold increases further to $58,656/year.\n\nAction Required: We recommend auditing your employee classifications immediately. Employees earning below the new threshold who work over 40 hours/week must be paid overtime.\n\nPlease contact us to review your payroll compliance before the July 1 deadline.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'irs-bonus-depreciation-2024',
    title: 'Bonus Depreciation Phases Down to 60% in 2024',
    summary: 'Section 168(k) bonus depreciation drops from 80% in 2023 to 60% in 2024, continuing phase-down through 2026.',
    fullText: 'Under the Tax Cuts and Jobs Act schedule, bonus depreciation for qualified property placed in service in 2024 is 60% (down from 80% in 2023). The phase-down continues: 40% in 2025, 20% in 2026, 0% in 2027 and beyond. Section 179 expensing ($1.22M limit in 2024) remains a viable alternative for small businesses.',
    effectiveDate: '2024-01-01',
    publishedDate: '2023-12-01',
    severity: 'important',
    source: 'IRS',
    affectedIndustries: ['Construction', 'Manufacturing', 'Transportation', 'Technology'],
    affectedStates: [],
    tags: ['depreciation', 'bonus depreciation', 'Section 179', 'TCJA', 'equipment'],
    actionRequired: 'Model bonus depreciation impact for clients purchasing equipment — compare 60% bonus vs. full Section 179.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nImportant update on equipment and asset depreciation for 2024:\n\nBonus depreciation has decreased to 60% this year (from 80% in 2023). If you are planning to purchase equipment, vehicles, or other business property, the timing of those purchases affects your tax deductions.\n\nSection 179 expensing (up to $1.22 million) remains available as an alternative.\n\nAction Required: If you are considering significant asset purchases this year, please contact us before completing the purchase so we can model the optimal tax strategy.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'irs-research-credit-2024',
    title: 'R&D Tax Credit Documentation Requirements Tightened',
    summary: 'IRS increased scrutiny on R&D credit claims requiring detailed contemporaneous records of qualifying research activities.',
    fullText: 'The IRS has increased audit focus on Research and Development (R&D) tax credit claims under IRC Section 41. Claims must now include: a description of each business component, all research activities performed, individuals who performed each activity, and information each individual sought to discover. Retroactive claims require Form 6765 with detailed attachments.',
    effectiveDate: '2024-01-01',
    publishedDate: '2024-01-15',
    severity: 'important',
    source: 'IRS',
    affectedIndustries: ['Technology', 'Manufacturing', 'Healthcare', 'Professional Services'],
    affectedStates: [],
    tags: ['R&D credit', 'research', 'documentation', 'audit', 'Section 41'],
    actionRequired: 'Ensure R&D credit clients maintain project-level documentation; review existing claims for compliance.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nThe IRS has tightened documentation requirements for Research and Development (R&D) tax credits.\n\nIf you claim R&D credits, you must now maintain detailed records of: qualifying research projects, specific activities performed, employees involved, and the technical uncertainty being investigated.\n\nAction Required: Please begin documenting your R&D activities on a project-by-project basis. We recommend implementing a time-tracking system for employees working on qualifying research.\n\nContact us to review your current R&D documentation practices.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'irs-ertc-audit-2024',
    title: 'IRS Aggressively Auditing Employee Retention Tax Credit Claims',
    summary: 'IRS launched 500+ audits and criminal investigations into improper ERTC claims; recapture and penalties apply.',
    fullText: 'The IRS is conducting over 500 civil audits and 300 criminal investigations related to improper Employee Retention Tax Credit (ERTC) claims. A voluntary disclosure program allowed businesses to repay 80% of improper claims without penalties (expired March 22, 2024). Going forward, businesses with invalid ERTC claims face full repayment plus 20% penalty and interest.',
    effectiveDate: '2024-03-22',
    publishedDate: '2024-01-03',
    severity: 'critical',
    source: 'IRS',
    affectedIndustries: [],
    affectedStates: [],
    tags: ['ERTC', 'ERC', 'audit', 'fraud', 'penalties', 'COVID'],
    actionRequired: 'Review all ERTC claims for validity; advise clients to consult legal counsel if claims are questionable.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nUrgent advisory regarding Employee Retention Tax Credit (ERTC) claims:\n\nThe IRS is aggressively auditing ERTC claims and has launched hundreds of criminal investigations. If you received ERTC funds, we strongly recommend a compliance review.\n\nRed flags the IRS is targeting: claiming credits for all 2020-2021 periods without qualification analysis, using revenue decline tests incorrectly, or claims submitted by aggressive third-party promoters.\n\nAction Required: Please contact us immediately if you received ERTC funds so we can review your eligibility documentation.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'boi-cta-2024',
    title: 'Corporate Transparency Act: Beneficial Ownership Reporting Deadline',
    summary: 'FinCEN requires most small businesses to file Beneficial Ownership Information reports — existing companies by Jan 1, 2025.',
    fullText: 'The Corporate Transparency Act (CTA) requires most small businesses, LLCs, and corporations to file Beneficial Ownership Information (BOI) reports with FinCEN. Existing companies (formed before January 1, 2024) must file by January 1, 2025. New companies formed in 2024 have 90 days to file. Reports require information about all beneficial owners (25%+ ownership or substantial control). Non-compliance penalties: $500/day and up to $10,000 criminal fine.',
    effectiveDate: '2024-01-01',
    publishedDate: '2024-01-01',
    severity: 'critical',
    source: 'IRS',
    affectedIndustries: [],
    affectedStates: [],
    tags: ['CTA', 'BOI', 'FinCEN', 'beneficial ownership', 'compliance', 'LLC'],
    actionRequired: 'Alert all LLC/corporation clients to file BOI with FinCEN by Jan 1, 2025 or face $500/day penalties.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nCritical compliance deadline: The Corporate Transparency Act requires your business to file a Beneficial Ownership Information (BOI) report with FinCEN.\n\nDeadline: January 1, 2025 (for existing businesses)\nPenalty for non-compliance: $500 per day, up to $10,000 criminal penalty\n\nYou must report information about all individuals who own 25% or more of the company or exercise substantial control.\n\nAction Required: File your BOI report at fincen.gov/boi before the deadline. This is a one-time filing unless ownership information changes.\n\nPlease contact us if you need assistance.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'ca-ab5-2024',
    title: 'California AB5: Independent Contractor Classification Rules',
    summary: 'California\'s ABC test remains in effect — most workers are employees unless they pass all 3 criteria.',
    fullText: 'California\'s AB5 law (as amended by AB2257) continues to apply the ABC test for worker classification. A worker is an employee unless: (A) free from control in performance; (B) performs work outside the usual course of business; and (C) is customarily engaged in an independent trade. Misclassification penalties include back wages, taxes, benefits, and civil penalties up to $25,000 per violation.',
    effectiveDate: '2024-01-01',
    publishedDate: '2024-01-01',
    severity: 'critical',
    source: 'State',
    affectedIndustries: [],
    affectedStates: ['CA'],
    tags: ['California', 'independent contractor', 'AB5', 'ABC test', 'misclassification'],
    actionRequired: 'Review California client worker classifications; apply ABC test to all contractors.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nImportant reminder regarding worker classification in California:\n\nUnder AB5, most workers must be classified as employees unless they pass all three parts of the ABC test. Misclassification can result in penalties up to $25,000 per violation plus back taxes and benefits.\n\nAction Required: Please review your independent contractor agreements. We recommend we conduct a classification audit of your contractor relationships.\n\nContact us to schedule a review.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'irs-crypto-2024',
    title: 'IRS Requires Reporting All Digital Asset Transactions',
    summary: '2024 Form 1040 requires disclosure of all digital asset transactions; new broker reporting rules take effect 2025.',
    fullText: 'The IRS requires taxpayers to answer the digital asset question on Form 1040 and report all taxable digital asset transactions. This includes cryptocurrency sales, exchanges, and payments. New broker reporting rules under the Infrastructure Investment and Jobs Act take effect for 2025 — brokers will issue 1099-DA forms. Failure to report results in penalties; the IRS uses blockchain analytics to identify unreported transactions.',
    effectiveDate: '2024-01-01',
    publishedDate: '2024-01-15',
    severity: 'important',
    source: 'IRS',
    affectedIndustries: [],
    affectedStates: [],
    tags: ['cryptocurrency', 'digital assets', 'Bitcoin', '1099-DA', 'reporting'],
    actionRequired: 'Obtain complete crypto transaction history from clients before preparing returns.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nReminder: All digital asset transactions must be reported to the IRS.\n\nThis includes: buying/selling cryptocurrency, exchanging one crypto for another, receiving crypto as payment or mining rewards, and using crypto to purchase goods or services.\n\nAction Required: Please provide us with a complete history of all cryptocurrency transactions for 2024. Many exchanges provide annual tax reports — please download and send these to us.\n\nNote: The IRS uses blockchain analytics and receives exchange reports to identify unreported transactions.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'irs-health-coverage-2024',
    title: 'ACA Employer Mandate: 2024 Penalties Increased',
    summary: 'ACA employer mandate penalties increased for 2024 — $2,970 per FTE for no coverage, $4,460 for inadequate coverage.',
    fullText: 'The IRS has released 2024 Affordable Care Act employer mandate penalties. For employers failing to offer minimum essential coverage (the "A" penalty), the fine is $2,970 per full-time employee (minus 30). For offering coverage that fails minimum value or affordability (the "B" penalty), the fine is $4,460 per affected employee who receives a premium tax credit. Applicable Large Employers (50+ FTEs) must file Forms 1094-C and 1095-C.',
    effectiveDate: '2024-01-01',
    publishedDate: '2024-01-10',
    severity: 'important',
    source: 'IRS',
    affectedIndustries: [],
    affectedStates: [],
    employeeMin: 50,
    tags: ['ACA', 'Affordable Care Act', 'employer mandate', 'health insurance', '1094-C', '1095-C'],
    actionRequired: 'Verify ALE clients (50+ FTEs) offer compliant health coverage; prepare 1094-C/1095-C filings.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\n2024 ACA Employer Mandate Update:\n\nAs an Applicable Large Employer (50+ full-time employees), you are required to offer minimum essential health coverage or face significant penalties.\n\n2024 penalties:\n• Not offering coverage: $2,970/employee/year\n• Inadequate coverage: $4,460/affected employee/year\n\nAction Required: Please confirm your health coverage offerings meet ACA minimum value and affordability standards. We will prepare your 1094-C and 1095-C filings due by March 31, 2024.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'irs-estimated-tax-2024',
    title: 'Underpayment Penalty Rate Remains at 8% for 2024',
    summary: 'IRS underpayment interest and penalty rate is 8% per year (Federal Short-Term Rate + 3%) for Q1 2024.',
    fullText: 'The IRS underpayment penalty interest rate for individuals is 8% for the first quarter of 2024, calculated as the Federal Short-Term Rate (5%) plus 3 percentage points. Self-employed individuals and those with significant non-wage income should ensure quarterly estimated tax payments cover at least 90% of 2024 tax or 100% of 2023 tax liability (110% for high-income taxpayers).',
    effectiveDate: '2024-01-01',
    publishedDate: '2023-11-28',
    severity: 'informational',
    source: 'IRS',
    affectedIndustries: [],
    affectedStates: [],
    tags: ['estimated tax', 'underpayment', 'quarterly payments', 'self-employed'],
    actionRequired: 'Advise clients to increase quarterly estimates given 8% underpayment penalty rate.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nReminder about 2024 estimated quarterly tax payments:\n\nThe IRS underpayment penalty rate is 8% for 2024 — the highest in over a decade. To avoid penalties, your quarterly payments should cover at least:\n• 90% of your estimated 2024 tax liability, OR\n• 100% of your 2023 tax liability (110% if your 2023 AGI exceeded $150,000)\n\nQuarterly due dates: April 15, June 17, September 16, 2024, and January 15, 2025.\n\nPlease contact us if you would like us to calculate your safe harbor estimated payments.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'dol-401k-fees-2024',
    title: 'DOL Fiduciary Rule: New Rollover Advice Standards',
    summary: 'DOL\'s expanded fiduciary rule takes effect September 2024, covering IRA rollover advice and one-time recommendations.',
    fullText: 'The Department of Labor expanded the definition of investment advice fiduciary under ERISA. Effective September 23, 2024, one-time rollover recommendations and IRA investment advice are covered. Advisors providing rollover advice must act in the client\'s best interest (not just suitable), disclose conflicts of interest, and charge only reasonable compensation. CPAs advising on rollovers may be subject to these standards.',
    effectiveDate: '2024-09-23',
    publishedDate: '2024-04-25',
    severity: 'important',
    source: 'DOL',
    affectedIndustries: ['Professional Services'],
    affectedStates: [],
    tags: ['fiduciary', 'DOL', '401k', 'IRA', 'rollover', 'ERISA'],
    actionRequired: 'Review whether rollover advice services trigger fiduciary obligations; update disclosure practices.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nImportant update regarding retirement account rollover advice:\n\nNew Department of Labor rules effective September 23, 2024 expand fiduciary standards to cover one-time rollover recommendations.\n\nIf you receive advice about rolling over your 401(k) into an IRA, your advisor must now act in your best interest and disclose any conflicts of interest.\n\nAction Required: No immediate action needed from you. We want you to be aware that we always provide advice in your best interest and will provide any required disclosures regarding our compensation.\n\nContact us with any questions about your retirement accounts.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'irs-home-office-2024',
    title: 'Home Office Deduction: Simplified Method Unchanged at $5/sq ft',
    summary: 'IRS simplified home office deduction remains at $5 per square foot, max 300 sq ft ($1,500 max deduction).',
    fullText: 'The IRS simplified method for home office deductions remains at $5 per square foot for 2024, with a maximum of 300 square feet ($1,500 maximum deduction). The regular method (actual expenses) allows for larger deductions but requires detailed recordkeeping. Note: Employees working from home cannot claim home office deductions — only self-employed individuals and business owners qualify.',
    effectiveDate: '2024-01-01',
    publishedDate: '2024-01-01',
    severity: 'informational',
    source: 'IRS',
    affectedIndustries: ['Professional Services', 'Technology', 'E-commerce'],
    affectedStates: [],
    tags: ['home office', 'deduction', 'self-employed', 'simplified method'],
    actionRequired: 'Advise self-employed clients to document home office space; compare simplified vs. actual methods.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nHome office deduction reminder for 2024:\n\nIf you use part of your home regularly and exclusively for business, you may deduct home office expenses.\n\nSimplified Method: $5/square foot × exclusive business space (max $1,500)\nRegular Method: Actual expenses proportional to business-use percentage (may yield a larger deduction)\n\nImportant: Only self-employed individuals and business owners qualify. Employees working from home cannot claim this deduction.\n\nAction Required: Measure your dedicated office space and document its exclusive business use. Contact us to determine which method provides the better deduction for your situation.\n\nWarm regards,\n[FIRM_NAME]',
  },
  {
    id: 'irs-qualified-opportunity-2024',
    title: 'Qualified Opportunity Zone Investment Deadline Extended',
    summary: 'Final deadline to invest capital gains in Qualified Opportunity Funds has passed; existing QOZ investments retain tax benefits.',
    fullText: 'The deadline to invest capital gains in Qualified Opportunity Funds (QOFs) to receive a 10% basis step-up has passed (December 31, 2021). However, existing QOZ investments still qualify for the 10-year gain exclusion if held until December 31, 2026, or sold after holding for 10+ years. Investors in QOZs should ensure annual QOF reporting compliance.',
    effectiveDate: '2024-01-01',
    publishedDate: '2024-01-01',
    severity: 'informational',
    source: 'IRS',
    affectedIndustries: ['Real Estate', 'Technology'],
    affectedStates: [],
    tags: ['QOZ', 'opportunity zones', 'capital gains', 'investment'],
    actionRequired: 'Review QOF investment compliance; prepare Form 8997 for clients with outstanding QOZ investments.',
    draftLetterTemplate: 'Dear [CLIENT_NAME],\n\nIf you have invested in Qualified Opportunity Funds (QOFs), here is an important update:\n\nExisting QOZ investments may still qualify for significant tax benefits:\n• Gain deferral until December 31, 2026\n• 10% basis step-up if invested before December 31, 2021\n• Complete exclusion of appreciation if held 10+ years\n\nAction Required: Please confirm you are filing Form 8997 annually to track your QOF investment and maintain compliance. Contact us to review your QOZ investment strategy.\n\nWarm regards,\n[FIRM_NAME]',
  },
]
