import Papa from 'papaparse'
import type { Transaction, ChartOfAccounts } from '@/types'
import type { CsvExportFormat, DetailColumnKey } from '@/lib/export/types'
import { DEFAULT_DETAIL_COLUMNS, headerLabel, rowForDetailColumn } from '@/lib/export/types'

const FOOTER = '"Generated by CloseBooks — closebooks-app.vercel.app"'

function footer(csv: string): string {
  return csv + '\n\n' + FOOTER
}

/** Legacy QuickBooks-style CSV (kept for compatibility). */
export function buildQuickBooksCSV(transactions: Transaction[], clientName: string): string {
  const rows = transactions.map((t) => {
    const category = t.final_category ?? t.suggested_category ?? 'Uncategorized'
    const account = t.final_account_code
      ? `${t.final_account_code} - ${t.final_category ?? category}`
      : t.suggested_account_code
        ? `${t.suggested_account_code} - ${category}`
        : 'Uncategorized'
    const amount = t.type === 'debit' ? -t.amount : t.amount
    return {
      Date: t.date,
      Account: account,
      Description: t.description,
      Amount: amount.toFixed(2),
      Category: category,
      Class: clientName,
    }
  })
  return footer(Papa.unparse(rows, { header: true }))
}

export function buildStandardCSV(transactions: Transaction[]): string {
  const rows = transactions.map((t) => {
    const category = t.final_category ?? t.suggested_category ?? ''
    const accountCode = t.final_account_code ?? t.suggested_account_code ?? ''
    return {
      Date: t.date,
      Description: t.description,
      Category: category,
      'Account Code': accountCode,
      Debit: t.type === 'debit' ? t.amount.toFixed(2) : '',
      Credit: t.type === 'credit' ? t.amount.toFixed(2) : '',
      Status: t.status,
      Notes: t.notes ?? '',
    }
  })
  return footer(Papa.unparse(rows, { header: true }))
}

/**
 * QBO-style journal CSV: one line per transaction with debit/credit split
 * (simplified journal — not full multi-line JE; suitable for import prep).
 */
export function buildQboJournalCsv(transactions: Transaction[], clientName: string): string {
  const rows: Record<string, string>[] = []
  for (const t of transactions) {
    const cat = t.final_category ?? t.suggested_category ?? 'Uncategorized'
    const code = t.final_account_code ?? t.suggested_account_code ?? ''
    const jeNum = `${clientName.slice(0, 12)}-${t.date}`
    if (t.type === 'debit') {
      rows.push({
        'Journal No': jeNum,
        Date: t.date,
        'Account Name': cat,
        'Account Code': code,
        Description: t.description,
        Debit: t.amount.toFixed(2),
        Credit: '',
        Memo: clientName,
      })
    } else {
      rows.push({
        'Journal No': jeNum,
        Date: t.date,
        'Account Name': cat,
        'Account Code': code,
        Description: t.description,
        Debit: '',
        Credit: t.amount.toFixed(2),
        Memo: clientName,
      })
    }
  }
  return footer(Papa.unparse(rows, { header: true }))
}

/** Xero manual journal style CSV. */
export function buildXeroCsv(transactions: Transaction[], clientName: string): string {
  const rows: Record<string, string>[] = []
  for (const t of transactions) {
    const acc = t.final_category ?? t.suggested_category ?? 'Uncategorized'
    const code = t.final_account_code ?? t.suggested_account_code ?? ''
    rows.push({
      'Narration': `${clientName} — ${t.date}`,
      Date: t.date,
      'Account Code': code,
      Description: t.description,
      'Account Name': acc,
      ...(t.type === 'debit'
        ? { Debit: t.amount.toFixed(2), Credit: '' }
        : { Debit: '', Credit: t.amount.toFixed(2) }),
    })
  }
  return footer(Papa.unparse(rows, { header: true }))
}

export function buildTrialBalanceCsv(
  tx: Transaction[],
  chartOfAccounts: ChartOfAccounts[],
  clientName: string
): string {
  const byCode = new Map<string, { name: string; type: string; debit: number; credit: number }>()
  for (const a of chartOfAccounts) {
    byCode.set(a.code, { name: a.name, type: a.type, debit: 0, credit: 0 })
  }
  for (const t of tx) {
    const code = t.final_account_code ?? t.suggested_account_code ?? ''
    if (!code) continue
    const row =
      byCode.get(code) ?? {
        name: t.final_category ?? t.suggested_category ?? 'Unknown',
        type: 'expense',
        debit: 0,
        credit: 0,
      }
    if (t.type === 'debit') row.debit += t.amount
    else row.credit += t.amount
    byCode.set(code, row)
  }
  const rows = Array.from(byCode.entries())
    .map(([code, v]) => ({
      'Account Code': code,
      'Account Name': v.name,
      'Account Type': v.type,
      Debit: v.debit > 0 ? v.debit.toFixed(2) : '',
      Credit: v.credit > 0 ? v.credit.toFixed(2) : '',
      Client: clientName,
    }))
    .sort((a, b) => a['Account Code'].localeCompare(b['Account Code']))
  return footer(Papa.unparse(rows, { header: true }))
}

export function buildTransactionDetailCsv(
  transactions: Transaction[],
  columns: DetailColumnKey[] = DEFAULT_DETAIL_COLUMNS
): string {
  const rows = transactions.map((tx) => {
    const obj: Record<string, string | number> = {}
    for (const c of columns) {
      const v = rowForDetailColumn(tx, c)
      obj[headerLabel(c)] = typeof v === 'number' ? v : String(v)
    }
    return obj
  })
  return footer(Papa.unparse(rows, { header: true }))
}

/** QuickBooks Desktop IIF — minimal GENERAL JOURNAL style (verify in your QBD version). */
export function buildIif(transactions: Transaction[], clientName: string): string {
  const esc = (s: string) => s.replace(/\t/g, ' ').slice(0, 120)
  const lines: string[] = [
    '!TRNS',
    'TRNSID	TRNSTYPE	DATE	ACCNT	NAME	AMOUNT	MEMO',
    '!SPL',
    'SPLID	TRNSTYPE	DATE	ACCNT	NAME	AMOUNT	MEMO',
    '!ENDTRNS',
  ]
  let id = 0
  for (const t of transactions) {
    id++
    const acc = t.final_category ?? t.suggested_category ?? 'Uncategorized'
    const amt = t.type === 'debit' ? -Math.abs(t.amount) : Math.abs(t.amount)
    lines.push(`TRNS\t${id}\tGENERAL JOURNAL\t${t.date}\t${esc(acc)}\t${esc(clientName)}\t${amt.toFixed(2)}\t${esc(t.description)}`)
    lines.push(`SPL\t${id}\tGENERAL JOURNAL\t${t.date}\t${esc(acc)}\t\t${(-amt).toFixed(2)}\t${esc(t.description)}`)
    lines.push('ENDTRNS')
  }
  return lines.join('\n') + `\n\n# ${FOOTER}`
}

export function buildCsv(
  format: CsvExportFormat,
  transactions: Transaction[],
  clientName: string,
  chartOfAccounts: ChartOfAccounts[],
  detailColumns?: DetailColumnKey[]
): string {
  switch (format) {
    case 'quickbooks':
      return buildQuickBooksCSV(transactions, clientName)
    case 'standard':
      return buildStandardCSV(transactions)
    case 'qbo_journal_csv':
      return buildQboJournalCsv(transactions, clientName)
    case 'xero':
      return buildXeroCsv(transactions, clientName)
    case 'trial_balance':
      return buildTrialBalanceCsv(transactions, chartOfAccounts, clientName)
    case 'transaction_detail':
      return buildTransactionDetailCsv(transactions, detailColumns)
    case 'iif':
      return buildIif(transactions, clientName)
    default:
      return buildStandardCSV(transactions)
  }
}

export function filenameForFormat(format: CsvExportFormat, clientName: string): string {
  const base = clientName.trim().replace(/[^a-zA-Z0-9_\-. ]/g, '_').replace(/\s+/g, '_')
  const d = new Date().toISOString().slice(0, 10)
  const ext = format === 'iif' ? 'iif' : 'csv'
  const suffix: Record<CsvExportFormat, string> = {
    quickbooks: 'qbo_style',
    standard: 'standard',
    qbo_journal_csv: 'qbo_journal',
    xero: 'xero',
    trial_balance: 'trial_balance',
    transaction_detail: 'transactions',
    iif: 'journal',
  }
  return `${base}_${suffix[format]}_${d}.${ext}`
}
