import { NextRequest, NextResponse } from 'next/server'
import { SMITH_CONSTRUCTION_RETURN } from '@/lib/tax-draft/demoReturnData'

type ExportFormat = 'drake' | 'lacerte' | 'pdf'

function buildDrakeExport(data: typeof SMITH_CONSTRUCTION_RETURN): string {
  const lines: string[] = []
  lines.push('DRAKE|TAX|VERSION|2024')
  lines.push(`ENTITY|${data.formType}|${data.taxYear}|${data.client}|${data.ein}`)

  for (const section of data.sections) {
    for (const line of section.lines) {
      if (line.currentAmount !== null) {
        lines.push(
          [
            'LINE',
            section.name.toUpperCase().replace(/\s+/g, '_'),
            line.lineNumber,
            line.description.replace(/\|/g, ' '),
            line.currentAmount,
            line.priorYearAmount ?? '',
            line.confidence,
          ].join('|')
        )
      }
    }
  }

  if (data.opportunities.length > 0) {
    lines.push('')
    lines.push('OPPORTUNITIES|START')
    for (const opp of data.opportunities) {
      lines.push(
        `OPP|${opp.title}|${opp.estimatedSavings}|${opp.confidence}|${opp.lawReference}`
      )
    }
    lines.push('OPPORTUNITIES|END')
  }

  return lines.join('\n')
}

function buildLacerteExport(data: typeof SMITH_CONSTRUCTION_RETURN): string {
  const rows: string[][] = []
  rows.push(['Section', 'Line', 'Description', 'Current Year', 'Prior Year', 'Confidence', 'Law Reference'])

  for (const section of data.sections) {
    for (const line of section.lines) {
      rows.push([
        section.name,
        line.lineNumber,
        line.description,
        line.currentAmount !== null ? String(line.currentAmount) : '',
        line.priorYearAmount !== null ? String(line.priorYearAmount) : '',
        line.confidence,
        line.lawReference ?? '',
      ])
    }
  }

  return rows.map((r) => r.join('\t')).join('\n')
}

function buildPdfExport(data: typeof SMITH_CONSTRUCTION_RETURN): string {
  const lines: string[] = []

  lines.push('=' .repeat(70))
  lines.push(`FORM ${data.formType} — TAX YEAR ${data.taxYear}`)
  lines.push(`CLIENT: ${data.client}  |  EIN: ${data.ein}`)
  lines.push('Generated by CloseBooks TaxDraft AI')
  lines.push('=' .repeat(70))
  lines.push('')

  for (const section of data.sections) {
    lines.push('-'.repeat(70))
    lines.push(`  ${section.name.toUpperCase()}`)
    lines.push('-'.repeat(70))

    for (const line of section.lines) {
      const curr = line.currentAmount !== null
        ? `$${line.currentAmount.toLocaleString()}`
        : '—'
      const prior = line.priorYearAmount !== null
        ? `$${line.priorYearAmount.toLocaleString()}`
        : '—'

      lines.push(
        `  Line ${line.lineNumber.padEnd(6)} ${line.description.slice(0, 38).padEnd(40)} ${curr.padStart(14)}  (Prior: ${prior})`
      )

      if (line.reasoning) {
        const wrapped = line.reasoning.match(/.{1,60}(\s|$)/g) ?? [line.reasoning]
        lines.push('  ┌─ AI Annotation:')
        for (const chunk of wrapped) {
          lines.push(`  │  ${chunk.trim()}`)
        }
        if (line.lawReference) lines.push(`  │  Ref: ${line.lawReference}`)
        if (line.opportunity) lines.push(`  │  ★ ${line.opportunity}`)
        lines.push('  └─')
      }
      lines.push('')
    }
  }

  if (data.opportunities.length > 0) {
    lines.push('=' .repeat(70))
    lines.push('  TAX-SAVING OPPORTUNITIES')
    lines.push('=' .repeat(70))

    for (const opp of data.opportunities) {
      lines.push('')
      lines.push(`  ★ ${opp.title}  (${opp.lawReference})`)
      lines.push(`  Estimated Savings: $${opp.estimatedSavings.toLocaleString()}  |  Confidence: ${opp.confidence}`)
      const desc = opp.description.match(/.{1,65}(\s|$)/g) ?? [opp.description]
      for (const chunk of desc) lines.push(`    ${chunk.trim()}`)
      lines.push(`  Action Required: ${opp.actionRequired}`)
    }

    lines.push('')
    lines.push(`  TOTAL POTENTIAL SAVINGS: $${data.totalOpportunitySavings.toLocaleString()}`)
  }

  lines.push('')
  lines.push('=' .repeat(70))
  lines.push(`  Generated ${new Date().toLocaleDateString()} — CloseBooks TaxDraft AI`)
  lines.push('  This draft is for CPA review only. Not for filing as-is.')
  lines.push('=' .repeat(70))

  return lines.join('\n')
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const { returnId, format } = body as { returnId: string; format: ExportFormat }

    if (!returnId || !format) {
      return NextResponse.json({ error: 'returnId and format are required' }, { status: 400 })
    }

    // For demo: always use Smith Construction data
    const data = SMITH_CONSTRUCTION_RETURN

    let content: string
    let contentType: string
    let filename: string

    switch (format) {
      case 'drake':
        content = buildDrakeExport(data)
        contentType = 'text/plain'
        filename = `${data.client.replace(/\s+/g, '_')}_${data.formType}_${data.taxYear}.drf`
        break
      case 'lacerte':
        content = buildLacerteExport(data)
        contentType = 'text/tab-separated-values'
        filename = `${data.client.replace(/\s+/g, '_')}_${data.formType}_${data.taxYear}.tab`
        break
      case 'pdf':
        content = buildPdfExport(data)
        contentType = 'text/plain'
        filename = `${data.client.replace(/\s+/g, '_')}_${data.formType}_${data.taxYear}_annotated.txt`
        break
      default:
        return NextResponse.json({ error: 'Invalid format. Use: drake, lacerte, pdf' }, { status: 400 })
    }

    return new NextResponse(content, {
      status: 200,
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Cache-Control': 'no-store',
      },
    })
  } catch (err) {
    console.error('Export error:', err)
    return NextResponse.json({ error: 'Export failed' }, { status: 500 })
  }
}
