import type { ClientMetrics } from './metricsCalculator'

export interface DraftedEmail {
  subject: string
  body: string
}

export async function draftRadarEmail(
  clientName: string,
  status: 'yellow' | 'red',
  metrics: ClientMetrics
): Promise<DraftedEmail> {
  try {
    const response = await fetch('/api/radar/draft-email', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        clientName,
        issue:
          status === 'red'
            ? 'Critical cash flow alert — immediate action required'
            : 'Financial health warning — proactive review recommended',
        metrics,
      }),
    })

    if (!response.ok) {
      const err = await response.json().catch(() => ({}))
      throw new Error((err as { error?: string }).error ?? `HTTP ${response.status}`)
    }

    const data = await response.json() as { subject: string; body: string }
    return { subject: data.subject, body: data.body }
  } catch (err) {
    // Fallback template if API fails
    const urgency = status === 'red' ? 'urgent' : 'important'
    const runway = metrics.runwayDays
    const burn = metrics.monthlyBurn.toLocaleString('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0,
    })

    return {
      subject: `[${status === 'red' ? 'Action Required' : 'Heads Up'}] ${clientName} — Financial Health Review`,
      body: `Hi ${clientName} Team,

I wanted to reach out regarding some ${urgency} findings from our recent financial analysis.

Current Situation:
• Cash Balance: $${metrics.cashBalance.toLocaleString()}
• Monthly Burn Rate: ${burn}
• Cash Runway: ${runway} days
• AR Days Outstanding: ${metrics.arDays} days

${
  status === 'red'
    ? `We're seeing some concerning trends in your cash position. With only ${runway} days of runway at the current burn rate, we need to schedule a call this week to discuss immediate steps.`
    : `While your business is operating, there are some areas worth addressing proactively to strengthen your financial position.`
}

Recommended Next Steps:
1. Review and prioritize outstanding receivables
2. Identify any discretionary spending that can be deferred
3. Schedule a 30-minute review call with our team

Please reply to this email or book a time at your convenience.

Best regards,
Your CloseBooks CPA Team

---
This analysis was generated by CloseBooks Financial Radar.`,
    }
  }
}
